//
//  ManagerApprovalViews.swift
//  luxury
//
//  Created by Aditya Chauhan on 15/05/26.
//

import SwiftUI

struct ASTApprovalView: View {
    let ast: AST
    @Environment(\.dismiss) private var dismiss
    @Environment(Router.self) private var router
    @State private var state: ApprovalState = .waiting
    @State private var clientName = "Fetching..."
    @State private var productName = "Fetching..."
    @State private var errorMessage: String? = nil
    @State private var showSuccessAlert = false

    var body: some View {
        ManagerDecisionView(
            title:   "After Sales Ticket",
            heading: "Ticket #\(ast.id.uuidString.prefix(6).uppercased())",
            detail:  "\(clientName) · \(productName)\nGenerated by: \(ast.metadata?.createdBy ?? "Unknown Advisor")\nWarranty: \(ast.warrantyStatus?.capitalized ?? "Unknown")\nNotes: \(ast.description ?? "None")\nRemarks: \(ast.remark ?? "None")",
            photoUrls: ast.metadata?.photos,
            state:   $state,
            dismiss: dismiss,
            trackAction: {
                let trackingDetails = ASTDetails(
                    id: ast.id,
                    status: ast.status,
                    description: ast.description,
                    remark: ast.remark,
                    catalogs: nil,
                    client: nil
                )
                router.push(SARoute.afterSalesTracking(trackingDetails))
            }
        )
        .overlay(
            Group {
                if let error = errorMessage {
                    VStack {
                        Spacer()
                        Text(error)
                            .font(AppFonts.sansSerif(size: 14))
                            .foregroundStyle(.white)
                            .padding()
                            .background(AppColors.error.opacity(0.9))
                            .clipShape(RoundedRectangle(cornerRadius: 10))
                            .padding(.bottom, 100)
                            .transition(.move(edge: .bottom).combined(with: .opacity))
                            .onAppear {
                                DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
                                    withAnimation { errorMessage = nil }
                                }
                            }
                    }
                }
            }
        )
        .alert("Success", isPresented: $showSuccessAlert) {
            Button("OK") { dismiss() }
        } message: {
            Text("Ticket has been successfully \(state.rawValue).")
        }
        .onAppear {
            let lower = ast.status.lowercased()
            if ["approved", "in_progress", "dispatched", "ready"].contains(lower) {
                state = .approved
            } else if lower == "rejected" || lower == "declined" {
                state = .rejected
            }
        }
        .task {
            if let clientId = ast.clientId {
                if let client = try? await ClientService().fetchClient(id: clientId) {
                    clientName = client.name
                } else {
                    clientName = "Unknown Client"
                }
            } else {
                clientName = "Unknown Client"
            }
            if let catalog = try? await CatalogService().fetchCatalogs().first(where: { $0.id == ast.productId }) {
                productName = catalog.name
            } else {
                productName = "Unknown Product"
            }
        }
        .onChange(of: state) { _, newValue in
            if (newValue == .approved || newValue == .rejected) && ast.status.lowercased() != newValue.rawValue.lowercased() {
                Task {
                    do {
                        try await ASTService.shared.updateASTStatus(astId: ast.id, newStatus: newValue.rawValue.lowercased())
                        await MainActor.run {
                            showSuccessAlert = true
                        }
                    } catch {
                        print("Failed to update status: \(error)")
                        await MainActor.run {
                            state = .waiting
                            errorMessage = "Failed to update: \(error.localizedDescription)"
                        }
                    }
                }
            }
        }
    }
}

struct WriteOffApprovalView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var state: ApprovalState = .waiting
    @State private var viewModel = ShrinkReportViewModel()
    
    var body: some View {
        ZStack {
            AppColors.background.ignoresSafeArea()
            
            VStack(spacing: 0) {
                CustomHeader(title: "Write-Off Approval", showBackButton: true, backAction: { dismiss() }, isInline: true)
                
                ScrollView {
                    VStack(alignment: .leading, spacing: 24) {
                        
                        if viewModel.isLoading {
                            ProgressView().tint(AppColors.gold)
                                .frame(maxWidth: .infinity, minHeight: 300)
                        } else if viewModel.recentWriteOffs.isEmpty {
                            VStack(spacing: 12) {
                                Image(systemName: "checkmark.shield.fill")
                                    .font(.system(size: 40))
                                    .foregroundStyle(AppColors.success)
                                Text("No pending write-offs.")
                                    .font(AppFonts.sansSerif(size: 16))
                                    .foregroundStyle(AppColors.secondary)
                            }
                            .frame(maxWidth: .infinity, minHeight: 300)
                        } else {
                            // Status Badge
                            StatusBadge(
                                text: LocalizedStringKey(state.rawValue),
                                status: state == .approved ? .success : state == .rejected ? .error : .pending
                            )
                            .padding(.horizontal, 24)
                            
                            // Dynamic Details
                            VStack(alignment: .leading, spacing: 8) {
                                Text("Inventory Write-Off \(viewModel.totalShrinkValue)")
                                    .font(AppFonts.serif(size: 28, weight: .bold))
                                    .foregroundStyle(.white)
                                
                                Text("\(viewModel.recentWriteOffs.count) variance items • Audit trail locked")
                                    .font(AppFonts.sansSerif(size: 14))
                                    .foregroundStyle(AppColors.secondary)
                            }
                            .padding(.horizontal, 24)
                            
                            // Variance Items List
                            VStack(alignment: .leading, spacing: 16) {
                                Text("DISCREPANCY DETAILS")
                                    .font(AppFonts.sansSerif(size: 11, weight: .bold))
                                    .foregroundStyle(AppColors.secondary)
                                    .kerning(1.5)
                                    .padding(.horizontal, 24)
                                
                                VStack(spacing: 0) {
                                    ForEach(viewModel.recentWriteOffs) { item in
                                        HStack(alignment: .top) {
                                            VStack(alignment: .leading, spacing: 4) {
                                                Text(item.name)
                                                    .font(AppFonts.sansSerif(size: 14, weight: .semibold))
                                                    .foregroundStyle(.white)
                                                Text(item.reason)
                                                    .font(AppFonts.sansSerif(size: 12))
                                                    .foregroundStyle(AppColors.error)
                                            }
                                            Spacer()
                                            
                                            let variance = item.actual - item.expected
                                            Text(variance > 0 ? "+\(variance)" : "\(variance)")
                                                .font(AppFonts.sansSerif(size: 16, weight: .bold))
                                                .foregroundStyle(variance > 0 ? AppColors.success : AppColors.error)
                                        }
                                        .padding(.vertical, 16)
                                        .padding(.horizontal, 20)
                                        .background(AppColors.surface)
                                        
                                        Divider().background(AppColors.border)
                                    }
                                }
                                .clipShape(RoundedRectangle(cornerRadius: 16))
                                .overlay(RoundedRectangle(cornerRadius: 16).stroke(AppColors.gold15, lineWidth: 1))
                                .padding(.horizontal, 24)
                            }
                            
                            // Approve / Reject Actions
                            if state == .waiting {
                                VStack(spacing: 12) {
                                    CustomButton(title: "Approve Write-Off", action: {
                                        state = .approved
                                        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) { dismiss() }
                                    })
                                    
                                    CustomOutlineButton(title: "Reject & Request Recount", icon: AnyView(EmptyView()), action: {
                                        state = .rejected
                                        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) { dismiss() }
                                    })
                                }
                                .padding(.horizontal, 24)
                                .padding(.top, 24)
                            }
                        }
                    }
                    .padding(.top, 16)
                    .padding(.bottom, 40)
                }
            }
        }
        .toolbar(.hidden, for: .navigationBar)
        .onAppear {
            viewModel.fetchInventory()
        }
    }
}

struct FullScreenPhoto: Identifiable {
    let id = UUID()
    let url: URL
}

private struct ManagerDecisionView: View {
    let title:   LocalizedStringKey
    let heading: LocalizedStringKey
    let detail:  LocalizedStringKey
    let photoUrls: [String]?
    @Binding var state: ApprovalState
    let dismiss: DismissAction
    let trackAction: (() -> Void)?
    
    @State private var selectedPhoto: FullScreenPhoto? = nil

    init(title: LocalizedStringKey, heading: LocalizedStringKey, detail: LocalizedStringKey, photoUrls: [String]? = nil, state: Binding<ApprovalState>, dismiss: DismissAction, trackAction: (() -> Void)? = nil) {
        self.title = title
        self.heading = heading
        self.detail = detail
        self.photoUrls = photoUrls
        self._state = state
        self.dismiss = dismiss
        self.trackAction = trackAction
    }

    var body: some View {
        ZStack {
            AppColors.background.ignoresSafeArea()

            VStack(spacing: 0) {

                ScrollView(showsIndicators: false) {
                    VStack(alignment: .leading, spacing: 18) {
                        StatusBadge(
                            text:   LocalizedStringKey(state.rawValue),
                            status: state == .approved ? .success : state == .rejected ? .error : .pending
                        )

                        VStack(alignment: .leading, spacing: 10) {
                            Text(heading)
                                .font(AppFonts.serif(size: 24, weight: .medium))
                                .foregroundStyle(AppColors.text)
                            Text(detail)
                                .font(AppFonts.sansSerif(size: 13))
                                .foregroundStyle(AppColors.secondary)
                                .lineSpacing(4)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(16)
                        .background(AppColors.surface)
                        .clipShape(RoundedRectangle(cornerRadius: 12))

                        if let urls = photoUrls, !urls.isEmpty {
                            VStack(alignment: .leading, spacing: 12) {
                                Text("CONDITION PHOTOS")
                                    .font(AppFonts.sansSerif(size: 10, weight: .bold))
                                    .foregroundStyle(AppColors.secondary)
                                    .kerning(1.5)
                                
                                ScrollView(.horizontal, showsIndicators: false) {
                                    HStack(spacing: 12) {
                                        ForEach(urls, id: \.self) { urlString in
                                            if let url = URL(string: urlString) {
                                                Button(action: {
                                                    selectedPhoto = FullScreenPhoto(url: url)
                                                }) {
                                                    AsyncImage(url: url) { phase in
                                                        if let image = phase.image {
                                                            image
                                                                .resizable()
                                                                .scaledToFill()
                                                        } else if phase.error != nil {
                                                            Image(systemName: "exclamationmark.triangle")
                                                                .foregroundStyle(AppColors.error)
                                                        } else {
                                                            ProgressView()
                                                        }
                                                    }
                                                    .frame(width: 120, height: 120)
                                                    .background(AppColors.surface2)
                                                    .clipShape(RoundedRectangle(cornerRadius: 12))
                                                }
                                                .buttonStyle(.plain)
                                            }
                                        }
                                    }
                                }
                            }
                            .padding(16)
                            .background(AppColors.surface)
                            .clipShape(RoundedRectangle(cornerRadius: 12))
                        }


                        if let trackAction = trackAction {
                            Button(action: trackAction) {
                                HStack(spacing: 8) {
                                    Image(systemName: "wrench.and.screwdriver.fill")
                                    Text("Track Service Details")
                                }
                                .font(AppFonts.sansSerif(size: 15, weight: .bold))
                                .foregroundStyle(AppColors.background)
                                .frame(maxWidth: .infinity)
                                .frame(height: 54)
                                .background(AppColors.gold)
                                .clipShape(RoundedRectangle(cornerRadius: 14))
                            }
                            .buttonStyle(.plain)
                        }

                        if state == .waiting {
                            HStack(spacing: 12) {
                                CustomOutlineButton(
                                    title: "Reject",
                                    icon: AnyView(Image(systemName: "xmark.circle")),
                                    action: { state = .rejected }
                                )
                                CustomButton(
                                    title: "Approve",
                                    icon: AnyView(Image(systemName: "checkmark.circle")),
                                    action: { state = .approved }
                                )
                            }
                        }
                    }
                    .padding(.horizontal, 24)
                    .padding(.vertical, 20)
                }
            }
        }
        .navigationTitle("Details")
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(AppColors.background, for: .navigationBar)
        .toolbarBackground(.visible, for: .navigationBar)
        .toolbarColorScheme(.dark, for: .navigationBar)
        .fullScreenCover(item: $selectedPhoto) { photo in
            ZStack {
                AppColors.background.ignoresSafeArea()
                
                VStack(spacing: 0) {
                    HStack {
                        Spacer()
                        Button(action: {
                            selectedPhoto = nil
                        }) {
                            Image(systemName: "xmark.circle.fill")
                                .font(.system(size: 32))
                                .foregroundStyle(.white.opacity(0.8), .black.opacity(0.4))
                        }
                        .buttonStyle(.plain)
                        .padding(.trailing, 20)
                        .padding(.top, 16)
                        .padding(.bottom, 8)
                    }
                    
                    AsyncImage(url: photo.url) { phase in
                        if let image = phase.image {
                            image
                                .resizable()
                                .scaledToFit()
                        } else if phase.error != nil {
                            VStack(spacing: 12) {
                                Image(systemName: "exclamationmark.triangle")
                                    .font(.system(size: 40))
                                    .foregroundStyle(AppColors.error)
                                Text("Failed to load image")
                                    .font(AppFonts.sansSerif(size: 14))
                                    .foregroundStyle(AppColors.secondary)
                            }
                            .frame(maxWidth: .infinity, maxHeight: .infinity)
                        } else {
                            ProgressView()
                                .scaleEffect(1.5)
                                .tint(.white)
                                .frame(maxWidth: .infinity, maxHeight: .infinity)
                        }
                    }
                    
                    Spacer()
                }
            }
        }
    }
}

#Preview("Write-Off Approval") {
    WriteOffApprovalView()
}
